permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: Bob Weboster
  email: fealonelei@gmail.com
  link: 
  weibo: 
  github: 

# 站点信息
title: Blog of fealonelei 
description: Blog of fealonelei
url: fealonlei.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7xi6q9.com1.z0.glb.clouddn.com/博客头像-木下.JPG
favicon: 

# google analytics 设置
ga:
  id: UA-57437179-2
  url: fealonelei.github.io

# disqus 设置
disqus:
  shortname: fealoneleib
