permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: Bob Weboster
  email: fealonelei@gmail.com
  link: 
  weibo: 
  github: 

# 站点信息
title: Blog of fealonelei 
description: Blog of fealonelei
url: 
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: 
favicon: 

# google analytics 设置
ga:
  id: UA-57437179-2
  url: fealonelei.github.io

# disqus 设置
disqus:
  shortname: disqus_VWMe8Qy39T
